// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwzopvINHKcmnc9Vw4wy-V8gbGuK3ULU4',
    appId: '1:503453976374:web:2d98b0f49dc90295065597',
    messagingSenderId: '503453976374',
    projectId: 'authfirebase-226e5',
    authDomain: 'authfirebase-226e5.firebaseapp.com',
    storageBucket: 'authfirebase-226e5.appspot.com',
    measurementId: 'G-YRWK57QTXM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe9bt4wlgQ09JcnxkiaHFPfV9Uf63oNmw',
    appId: '1:503453976374:android:f8e7706b206c4ea7065597',
    messagingSenderId: '503453976374',
    projectId: 'authfirebase-226e5',
    storageBucket: 'authfirebase-226e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZU-BHYV10xiG4lBT6TAmDhSjuo9-4Ro',
    appId: '1:503453976374:ios:f06a63b03a836d9a065597',
    messagingSenderId: '503453976374',
    projectId: 'authfirebase-226e5',
    storageBucket: 'authfirebase-226e5.appspot.com',
    iosBundleId: 'com.example.myFirstFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZU-BHYV10xiG4lBT6TAmDhSjuo9-4Ro',
    appId: '1:503453976374:ios:192761b2a8a49521065597',
    messagingSenderId: '503453976374',
    projectId: 'authfirebase-226e5',
    storageBucket: 'authfirebase-226e5.appspot.com',
    iosBundleId: 'com.example.myFirstFlutter.RunnerTests',
  );
}
